create table if not exists public.entries (
  id bigint generated by default as identity primary key,
  date text not null,
  worker text not null,
  customer text not null default '',
  property text not null default '',
  service_name text not null default '',
  hours double precision not null default 0,
  entry_type text not null default 'hourly',
  rate double precision not null default 30,
  amount double precision not null default 0,
  work_order text not null default '',
  job_description text not null default '',
  summary text not null default ''
);

create table if not exists public.monthly_reports (
  month text primary key,
  invoice_name text not null default '',
  invoice_number text not null default '',
  billing_date text not null default '',
  finalized_at text not null default '',
  pdf_path text not null default '',
  status text not null default 'open'
);

alter table public.entries enable row level security;
alter table public.monthly_reports enable row level security;

create policy if not exists "entries_authenticated_all" on public.entries
for all to authenticated
using (true)
with check (true);

create policy if not exists "monthly_reports_authenticated_all" on public.monthly_reports
for all to authenticated
using (true)
with check (true);
